from .algorithms import (
    BandResidual,
    FrontierSnapshot,
    IndexedResidualFrontier,
    PathResult,
    ResidualFrontier,
    WorkProfile,
    compare_indexed_against_dijkstra,
    compare_against_dijkstra,
    compare_v3_against_dijkstra,
    compare_v4_against_dijkstra,
    compare_v5_against_dijkstra,
    compare_v6_against_dijkstra,
    dijkstra_sssp,
    residual_frontier_sssp,
    residual_frontier_sssp_indexed,
    residual_frontier_sssp_v3,
    residual_frontier_sssp_v4,
    residual_frontier_sssp_v5,
    residual_frontier_sssp_v6,
)
from .analysis import (
    FrontierPolicy,
    GraphFeatures,
    ProbeSummary,
    analyse_graph,
    revise_frontier_policy,
    select_frontier_policy,
    select_operating_mode,
)
from .graphs import (
    Graph,
    add_undirected_edge,
    make_clustered_graph,
    make_grid_graph,
    make_irregular_weighted_graph,
    make_random_graph,
)
try:
    from .invariant_band import InvariantBandResult, solve_invariant_band_field

    _HAS_INVARIANT_BAND = True
except ImportError:  # numpy not installed; rfr[fast] extra
    _HAS_INVARIANT_BAND = False

from .spatial import (
    FieldLayers,
    Stencil,
    SpatialDifferentialResult,
    build_spatial_differential_graph,
    compare_spatial_solver_to_dijkstra,
    constant_gradient,
    eight_neighbour_stencil,
    extract_path,
    fixed_step_differential,
    four_neighbour_stencil,
    gradient_differential,
    min_differential_at,
    solve_spatial_differential_field,
    spatial_differential,
    von_neumann_neighbours,
)

__all__ = [
    "Graph",
    "FrontierPolicy",
    "GraphFeatures",
    "ProbeSummary",
    "BandResidual",
    "FrontierSnapshot",
    "IndexedResidualFrontier",
    "PathResult",
    "ResidualFrontier",
    "WorkProfile",
    "FieldLayers",
    "Stencil",
    "SpatialDifferentialResult",
    "add_undirected_edge",
    "analyse_graph",
    "build_spatial_differential_graph",
    "compare_spatial_solver_to_dijkstra",
    "compare_indexed_against_dijkstra",
    "compare_against_dijkstra",
    "constant_gradient",
    "compare_v3_against_dijkstra",
    "compare_v4_against_dijkstra",
    "compare_v5_against_dijkstra",
    "compare_v6_against_dijkstra",
    "dijkstra_sssp",
    "eight_neighbour_stencil",
    "extract_path",
    "fixed_step_differential",
    "four_neighbour_stencil",
    "gradient_differential",
    "make_clustered_graph",
    "make_grid_graph",
    "make_irregular_weighted_graph",
    "make_random_graph",
    "min_differential_at",
    "residual_frontier_sssp",
    "residual_frontier_sssp_indexed",
    "residual_frontier_sssp_v3",
    "residual_frontier_sssp_v4",
    "residual_frontier_sssp_v5",
    "residual_frontier_sssp_v6",
    "revise_frontier_policy",
    "select_frontier_policy",
    "select_operating_mode",
    "solve_spatial_differential_field",
    "spatial_differential",
    "von_neumann_neighbours",
]

if _HAS_INVARIANT_BAND:
    __all__ += ["InvariantBandResult", "solve_invariant_band_field"]
